<<<<<<< HEAD
name: Conditional Parallel Workflow
=======
name: Parallel Workflow
>>>>>>> 260afe9 (Добавлено выполнение выполнение задач в файле .yml)

on:
  push:
    branches:
      - main       # Запускается в ветке main
      - develop    # Запускается в ветке develop

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear NuGet cache
        run: rm -rf ~/.nuget/packages/

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Input/Input.csproj

      - name: Build Debug
        run: dotnet build Input/Input.csproj --configuration Debug

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Input/Input.csproj

      - name: Build Release
        run: dotnet build Input/Input.csproj --configuration Release

  test:
    needs: [build-debug, build-release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Tests/Tests.csproj

      - name: Run tests
<<<<<<< HEAD
        run: dotnet test Tests/Tests.csproj --configuration ${{ matrix.configuration }}

  analyze:
    if: github.ref == 'refs/heads/main'  # Выполняется только в ветке man
    needs: [build-debug, build-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run code analysis
        run: dotnet tool install -g dotnet-format && dotnet format Tests/Tests.csproj
=======
        run: dotnet test Tests/Tests.csproj --configuration ${{ matrix.configuration }}
>>>>>>> 260afe9 (Добавлено выполнение выполнение задач в файле .yml)
