name: tags

on:
  push:
    tags:
      - "release"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: zip
        if: github.reg == 'refs/tags/release'
        run: mkdir 
          zip -r release.zip Input/bin/Release
        
      - name: artifact
        if: github.reg == 'refs/tags/Release'
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip