name: Sequential Workflow с артефактами

on: [push]

jobs:
  # Задача сборки проекта
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build Input/Input.csproj --configuration Release

      - name: Загрузка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: build-output  # Имя артефакта
          path: Input/bin/Release/  # Путь к файлам, которые нужно загрузить

  # Задача тестирования
  test:
    needs: build  # Ожидаем завершения задачи build
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Скачивание артефактов
        uses: actions/download-artifact@v4
        with:
          name: build-output  # Скачиваем артефакт, созданный в задаче build

      - name: Настройка .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Запуск тестов
        run: dotnet test Tests/Tests.csproj --configuration Release