name: Sequential Workflow с матричной стратегией

on: [push]

jobs:
  # Задача сборки проекта
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]  # Матричная стратегия для разных конфигураций (Debug и Release)
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build Input/Input.csproj --configuration ${{ matrix.config }}  # Используем переменную из матрицы

  # Задача тестирования
  test:
    needs: build  # Ожидаем завершения всех задач сборки
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release]  # Матричная стратегия для разных конфигураций
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Запуск тестов
        run: dotnet test Tests/Tests.csproj --configuration ${{ matrix.config }}